PTerm-UI/TerminalEmulator.class.st
I factored out a method `#open:arguments:` from `#openShell:` so that other arguments can be passed.
Example which runs Bash as a login shell within one’s home directory:
```
TerminalEmulator open: '/bin/sh' arguments: #('-c' 'cd ~; exec /bin/bash -l')
```
=> Factored out method #open:arguments: from #openShell: on TerminalEmulator

PTerm-Core/LibPTerm.class.st, PTerm-Core/PTerm.class.st
This changes the signal that is sent when a Terminal window is closed to [SIGHUP](https://en.wikipedia.org/wiki/SIGHUP). The previous implementation is still used when the process was spawned in `PTerm>>#xspawn:env:` through the fallback, because I’m not sure whether using SIGHUP would be appropriate in that case.
=> Changed #close on PTerm to send the process SIGHUP

PTerm-Core/PTerm.class.st
This should fix the error _‘PrimitiveFailed: primitive #free in ExternalAddress failed’_ that occurs when reopening a Pharo image which was saved with open Terminal windows.
=> Made PTerm>>#waitForOutput not send #free to the ExternalAddress in ‘wbuff’ if it’s null

PTerm-Core/LibPTerm.class.st, PTerm-UI/TerminalEmulator.class.st
I had the problem that the `#vmDirectory` and `#workingDirectory` were not writable. I would suggest to use the `#localDirectory` instead for ‘Fonts’ and ‘libpterm.flib’.
=> Changed #fontsDir and LibPTerm’s #moduleName to use the #localDirectory

PTerm-UI/TerminalEmulatorXterm.class.st
I encountered use of SGR parameter value 22 in output from [webpack](https://webpack.js.org). See the message of commit efc922db216c271f for more details.
=> Extended TerminalEmulatorXterm with support for SGR parameter value 22

PTerm-UI/TerminalEmulator.class.st
This fixes a `MessageNotUnderstood` (and a `Deprecation`) that occurred in `TerminalEmulator>>#openOn:` in Pharo 9.
=> Changed TerminalEmulator>>#openOn: for compatibility with Pharo 9

PTerm-Core/PTerm.class.st
Example:
```
TerminalEmulator open: '/bin/bash' arguments: #('-c' 'for i in {1..10}; do date "+$i: %s"; done; read -n 1')
```
Problem: the output shown in the Terminal window did not always start at line 1.
The fix in commit c4794af5ffb93433 postpones creation of the Process for `#waitForOutput` to avoid announcing a PTermDataEvent before it can be received.
=> Moved creation of the Process for #waitForOutput in PTerm from #xspawn:env: to #run

PTerm-Core/PTermUTF8Encoder.class.st, PTerm-Test/PTermUTF8EncoderTest.class.st
See the messages of commits 510605c5c3fa29be and 9941aa6ff79fd029 for more details.
=> Fixed #nextCodePointFromStream: inherited from ZnUTF8Encoder returning values greater than that of #maximumUTFCode

PTerm-UI/TerminalEmulator.class.st, PTerm-UI/TerminalEmulatorMorph.class.st, README.md
This PR addresses the issue #31.
In pharo 9 and up, some keys such as non printable characters or meta/control keys are not handled by #keystroke event. Instead they are catched by #keyDown event. This PR allow PTerm to catch and process both events.
This PR also fixes the problem of displaying text cursor and text selection.
The solution is partially tested
=> Fix keyboard and mouse handling problem in pharo 9

PTerm-UI/TerminalEmulator.class.st
The PTerm window menu items also appeared in the window menu of other windows:
This PR fixes that so that the menu items only appear in the window menu of Terminal windows:
=> Remove PTerm window menu items from windows other than TerminalEmulator

PTerm-UI/TerminalEmulator.class.st
On Pharo9 `FreeTypeFontSelectorDialogWindow` is still used to select PTerm font.On Pharo10 however, this class no longer exists, `FontChooser` is used instead.
`FontChooser` exists on Pharo9, but the class interface is completely different from Pharo10. It is impossible to have a compatible use of this class for both Pharo9 and Pharo10
=> Fix font selector broken on Pharo 9 and Pharo 10

PTerm-UI/TerminalEmulator.class.st, PTerm-UI/TerminalEmulatorMorph.class.st, PTerm-UI/TerminalEmulatorXterm.class.st
This PR adds support for the ‘operating system command’ used in macOS’s Terminal to keep track of the shell’s working directory (see: https://github.com/lxsang/PTerm/pull/26#issuecomment-1154191290), and adds window menu items to browse and inspect the FileReference for that directory.
On macOS, one can open TerminalEmulator like this:
```smalltalk
TerminalEmulator open: '/usr/bin/env'
arguments: {
'TERM_PROGRAM=Apple_Terminal'.
'login'. '-pf'. OSEnvironment current at: 'LOGNAME' }
```
Then the window menu items ‘Browse working directory’ and ‘Inspect working directory’ should be enabled:
It’s best to merge PR https://github.com/lxsang/PTerm/pull/37 first, otherwise the window menus for other windows will be broken (because they include the PTerm menu items but the windows don’t …
=> Add support for the ‘operating system command’ used in macOS’s Terminal to keep track of the shell’s working directory

PTerm-UI/TerminalEmulator.class.st
In pull request #22, I changed the `#fontsDir` to a subdirectory of `#localDirectory`.
I think that was a mistake because that directory is not one of the directories used in the method `FreeTypeFontProvider>>#updateFontsFromSystem`. I probably didn’t notice the mistake because I already had the [‘fonts’ files](https://github.com/lxsang/PTerm/tree/c88a8812d102b3342184daf0b56fa652016d0185/fonts) in another directory (`~/Library/Fonts`, see the method `#macOSXFolderDirectories`).
In this pull request, I propose to change the `#fontsDir` to the directory given by `FreeTypeFontProvider current imageRelativeFontFolder`.
=> Change #fontsDir in TerminalEmulator to use the #imageRelativeFontFolder of the FreeTypeFontProvider

PTerm-UI/TerminalEmulatorXterm.class.st
This fixes a MessageNotUnderstood that occurs when running `TERM=xterm emacs` or `TERM=xterm nano`.
=> Fix message #setEmacsColours: not understood when running emacs or nano with TERM set to ‘xterm’

PTerm-UI/TerminalEmulator.class.st
In `TerminalEmulator class>>#menuCommandOn:`, the parent is set to `#MostUsedTools` which in Pharo 9 (and later) no longer exists. This pull request changes it to `#SystemTools` so that the “Terminal” menu item appears in the first group in the “System” menu (which also includes “File Browser”).
=> Change parent in #menuCommandOn: on TerminalEmulator from #MostUsedTools to #SystemTools

PTerm-Core/PTerm.class.st
This pull request changes `PTerm>>#close` to send SIGHUP (as suggested in a [review on pull request #54](https://github.com/lxsang/PTerm/pull/54#pullrequestreview-1611812064)).
=> Changed #close on PTerm to send the process SIGHUP again

PTerm-UI/TerminalEmulator.class.st, PTerm-UI/TerminalEmulatorMorph.class.st
- fix(#59): don't send NULL when only CTRL key is pressed
- fix(#36): add openDefaultShell class method to TerminalEmulator, world menu now  opend a shell based on the value of the SHELL environment variable
=> Minor fixes for issues 36 and 59

PTerm-Core/LibPTerm.class.st, PTerm-Core/PTerm.class.st
This pull request makes #xspawn:env: on PTerm use the library added to the VM in [pharo-vm pull request #742](https://github.com/pharo-project/pharo-vm/pull/742). The `posix_spawn` implementation is still used when the library is not available. Using the library fixes issue #58.
=> Make #xspawn:env: on PTerm use ‘libtty’

PTerm-Core/PTerm.class.st, PTerm-UI/TerminalEmulator.class.st, PTerm-UI/TerminalEmulatorLineMorph.class.st, PTerm-UI/TerminalEmulatorMorph.class.st, README.md
- #when:#do: is deprecated in Announcer, use #when:do:for: instead
- ScrollBar is renamed to ScrollBarMorph
This fix should be compatible with Pharo 9 and up
=> fix(#65): compatibility with Pharo 13

.properties, PTerm-Core/LibPTerm.class.st
This pull request fixes the calls of variadic functions in LibPTerm, see issue #67, specifically: [‘fcntl’](https://www.man7.org/linux/man-pages/man3/fcntl.3p.html), [‘ioctl’](https://www.man7.org/linux/man-pages/man3/ioctl.3p.html), [‘open’](https://www.man7.org/linux/man-pages/man3/open.3p.html) and [‘printf’](https://www.man7.org/linux/man-pages/man3/printf.3p.html).
=> Fix variadic function calls in LibPTerm
